### PR TITLE
fix(elements|ino-input): add autofocus prop to input element

### LINKED ISSUE #46: ino-input: autofocus does not work inside ino-card
### Describe the bug

Autofocus of ino-input does not work if wrapped by an ino-card element. 

### To Reproduce
1. Put ino-input with autofocus  enabled inside ino-card element
2. Reload Page
3. ino-input is not focused

### Expected behavior
Autofocus should work despite its parent element.

### PR DESCRIPTION
**Pull request by JCofman**
Closes #46 

Currently, we do not pass down the autofocus prop to the input element.

### CODE REVIEW

**Review by janivo — COMMENTED** [review]
Were there any issues for you with the autofocus functionality? Currently, we set the autofocus in line 269 like this:
```tsx
if (this.autoFocus) {
  this.textfield.focus();
}
```

**Comment by janivo** [comment]
Could you also resolve the conflicts?

**Comment by janivo** [comment]
Did you check if this fix resolves the problems mentioned in the linked issue?

**Comment by JCofman** [comment]
As far as I have understood the problem this should solve the issue. I have also tested it locally ;)

**Review by janivo — APPROVED** [review]

**Pull request merged**
