### PR TITLE
refactor(storybook): improve playground navigation

### LINKED ISSUE #1048: Automatically open playground submenu on clicking component in storybook navigation menu
### Feature Request

When clicking on a menu item in the storybook navigation, it should open the submenu AND navigate to the playground page for that component. Having to click two times for that is redundant.

### Additional context

Currently: 

https://github.com/inovex/elements/assets/22963121/0edfc00b-7b71-4f2d-8d8f-4e6d77116768

### PR DESCRIPTION
**Pull request by BingeCode**
Closes #1048

## Proposed Changes

Changed storybook documentation structure to allow for instant navigation to playground when component sidebar item is clicked. This better reflects expected behavior by the user.

https://github.com/inovex/elements/assets/48513535/d9c49062-d837-466c-8073-e4877190ff8a

https://github.com/inovex/elements/assets/48513535/dd7448a7-2036-4e87-9515-3682c74e546d

### CODE REVIEW

**Comment by janivo** [comment]
Waiting for #1063 to be merged, so all these formatting changes will be resolved

**Comment by MariaLStefan** [comment]
This change is pretty useful! Removes a lot of unnecessary clicks, but are we sure that we want to remove the navigation points `/Structure`, `/Input`, `/Graphic`, `/Button` and `/Notification`?

As our component library is quite extensive, I feel that removing the navigation points is a step backwards. Without the navigation points, you lose the overview of the functionalities of the individual components, as not everyone who visits the documentation for the first time immediately has a deeper understanding of the components. 

The components feel disorganized now, partly following the alphabet (or not) or collected into coherent groups of components that work together (pattern like).

I find the grouping into pattern-like groups (e.g. `/ino-list`, `/ino-table`, `/ino-nav`, `/ino-segment-group`, `/ino-tab-bar`) a welcome change, as in our current structure this is only given within a large functional group (e.g. `/Structure`) and related elements are only arranged under each other (example: `ino-list-divider`, `ino-list-item` and `ino-list`).

Unfortunately, these new groups are lost in this representation. It would be better to either list the individual components collectively above the groups or to merge them back into functional groups. The pattern-like groups can also be listed under the function groups or have their own points in the navigation.

**Comment by janivo** [comment]
@MariaLStefan  that's true, it would be great to keep those sections. I think the true culprit lies in our extra documentation files which will be deleted in #1090 anyway. Our navigation should work as expected once they are gone. So let's keep this open until #1090 is done and check again if it doesn't work.

**Comment by janivo** [comment]
as expected, can be closed because we've removed all documentation files. Storybook now recognizes everything as stories and opens those on first click

**Pull request closed without merging**
