### PR TITLE
feat(elements|ino-markdown-editor): support task lists

### LINKED ISSUE #642: (elements|ino-markdown-editor): Support for task list
### Feature Request

We need for our project a checklist support for instance to create a text based todo list. In order to this, it should be possible to check and uncheck the task items via click in preview mode.

### Description of the proposed solution

* https://tiptap.dev/api/nodes/task-list
* https://www.npmjs.com/package/markdown-it-task-lists (for Markdown Support)

### PR DESCRIPTION
**Pull request by BenPag**
Closes #642

## Proposed Changes

- add new icon "task-list"
- add tiptap extionsions for task list support
- refactored markdown parse process which was needed for the task list
  - Now I guess it is in general easier to integrate future extensions

### CODE REVIEW

**Comment by janivo** [comment]
elements-markdown-bug

Shouldn't I be able to check these in preview mode?

I also receive the followings errors:
image

**Comment by janivo** [comment]
How exactly do I use these without clicking the toolbar button?
elements-markdown

**Comment by BenPag** [comment]
> How exactly do I use these without clicking the toolbar button? elements-markdown [ elements-markdown ](https://user-images.githubusercontent.com/22963121/178763888-af9ef047-f8cb-4abc-a152-0e032a383813.gif) [ ](https://user-images.githubusercontent.com/22963121/178763888-af9ef047-f8cb-4abc-a152-0e032a383813.gif)

I have implemented a new input rule for that behavoir. Now you should type this markdown syntax in preview mode.

**Comment by janivo** [comment]
elements-markdown-bug

I still get this bug that I cannot check them in preview-mode

**Review by janivo — APPROVED** [review]

**Pull request merged**
