### PR TITLE
ci: remove add-issue-to-project workflow

### PR DESCRIPTION
**Pull request by janivo**
Workflow is replaced by Github internal workflows that are managed on our Github board.

### CODE REVIEW

**Comment by BenPag** [comment]
Please change PR title to a proper naming :)

**Comment by janivo** [comment]
> Please change PR title to a proper naming :)

What would be a better name in your opinion?

**Comment by BenPag** [comment]
> > Please change PR title to a proper naming :)
> 
> What would be a better name in your opinion?

ci: remove obsolete workflow file

**Comment by janivo** [comment]
> > > Please change PR title to a proper naming :)
> > 
> > 
> > What would be a better name in your opinion?
> 
> ci: remove obsolete workflow file
Ah whops, thought I was in another PR 😅

**Review by BenPag — APPROVED** [review]

**Pull request merged**
