### PR TITLE
chore(elements): update stencil to v2.0.3

### PR DESCRIPTION
**Pull request by P1NHE4D**
⚙️ **Changes:**
* Upgraded `stencil` to version `2.0.3`
* Upgraded `jest` to version `26.4.2`
* Upgraded `puppeteer` to version `5.3.1`
* Updated `nodejs` to version `14.5.0`
* Removed `typescript` from dev dependencies as it is included within the latest version of the `stencil` compiler
* Replaced all occurrences of `componentDidUnload()` with `disconnectedCallback()`

### CODE REVIEW

**Comment by P1NHE4D** [comment]
Regarding the WIP tag: The imports of `ComponentInterface` and `EventEmitter` are not working with the latest stencil version. The issue can be solved by replacing `@stencil/core` with `@stencil/core/internal`. However, the `internal` directory should only be used by the stencil compiler as breaking changes occur frequently. Maybe there's an easier way to solve it? I couldn't find any related issues on GitHub so far...

**Comment by janivo** [comment]
Just a tip: You can now open draft pull requests if you want to discuss some stuff inside a PR. See: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by janivo** [comment]
Maybe we can use this opportunity to upgrade our required Node Version as well?
Stencil [recommends 14.5.0](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#nodejs-update), so we should update our `.nvmrc` file so it's easier to switch to the recommended version.

**Comment by janivo** [comment]
> Regarding the WIP tag: The imports of `ComponentInterface` and `EventEmitter` are not working with the latest stencil version. The issue can be solved by replacing `@stencil/core` with `@stencil/core/internal`. However, the `internal` directory should only be used by the stencil compiler as breaking changes occur frequently. Maybe there's an easier way to solve it? I couldn't find any related issues on GitHub so far...

I have the same problem. I just found out that there is an error in the `node_modules/@stencil/core/internal/stencil-core/index.d.ts` from where we import these types.

This is the file:
```ts
export type = {
  ChildNode,
  ComponentOptions,
  ComponentDidLoad,
  ComponentDidUpdate,
  ComponentInterface,
  ComponentWillLoad,
  ComponentWillUpdate,
  EventEmitter,
  // ...
} from '../stencil-public-runtime';
// ...
```

How it should be:
```ts
export {
  ChildNode,
  ComponentOptions,
  ComponentDidLoad,
  ComponentDidUpdate,
  ComponentInterface,
  ComponentWillLoad,
  ComponentWillUpdate,
  EventEmitter,
  // ...
} from '../stencil-public-runtime';
// ...
```
At least that's what my IDE is telling me.
Kinda strange that we seem to be the only ones with that problem.

**Comment by P1NHE4D** [comment]
> > Regarding the WIP tag: The imports of `ComponentInterface` and `EventEmitter` are not working with the latest stencil version. The issue can be solved by replacing `@stencil/core` with `@stencil/core/internal`. However, the `internal` directory should only be used by the stencil compiler as breaking changes occur frequently. Maybe there's an easier way to solve it? I couldn't find any related issues on GitHub so far...
> 
> I have the same problem. I just found out that there is an error in the `node_modules/@stencil/core/internal/stencil-core/index.d.ts` from where we import these types.
> 
> This is the file:
> 
> ```ts
> export type = {
>   ChildNode,
>   ComponentOptions,
>   ComponentDidLoad,
>   ComponentDidUpdate,
>   ComponentInterface,
>   ComponentWillLoad,
>   ComponentWillUpdate,
>   EventEmitter,
>   // ...
> } from '../stencil-public-runtime';
> // ...
> ```
> 
> How it should be:
> 
> ```ts
> export {
>   ChildNode,
>   ComponentOptions,
>   ComponentDidLoad,
>   ComponentDidUpdate,
>   ComponentInterface,
>   ComponentWillLoad,
>   ComponentWillUpdate,
>   EventEmitter,
>   // ...
> } from '../stencil-public-runtime';
> // ...
> ```
> 
> At least that's what my IDE is telling me.
> Kinda strange that we seem to be the only ones with that problem.

That's odd. I had a similar issue with the angular configuration in the stencil config. 

> Regarding the WIP tag: The imports of `ComponentInterface` and `EventEmitter` are not working with the latest stencil version. The issue can be solved by replacing `@stencil/core` with `@stencil/core/internal`. However, the `internal` directory should only be used by the stencil compiler as breaking changes occur frequently. Maybe there's an easier way to solve it? I couldn't find any related issues on GitHub so far...

The issue can be solved by removing and reinstalling all node modules.

**Review by janivo — APPROVED** [review]

**Pull request merged**
