### PR TITLE
fix(elements|ino-datepicker): fix random year skipping in month picker

### LINKED ISSUE #215: ino-monthpicker: Skipping next and previous years on arrow click
### Describe the bug

When navigating through years by clicking the arrow icons, a click will either jump over multiple previous or next years. Sometimes another month is marked as well.

### To Reproduce

buggyMonthpicker(1)

### PR DESCRIPTION
**Pull request by janivo**
Closes #215 

## Proposed Changes

- Remove the custom logic to handle arrow clicks
- Add tests

### CODE REVIEW

**Comment by Sl1nd** [comment]
There is some strange behaviour in changing the year:


Uploading Bildschirmvideo aufnehmen 2021-01-27 um 14.52.57.mov…

**Comment by Sl1nd** [comment]
There is some strange behaviour on changing the Year in Monthpicker: 


https://user-images.githubusercontent.com/12165722/106001109-dab88080-60af-11eb-80bb-a305b36edee9.mov

**Comment by janivo** [comment]
I'll have a look at it. Thanks @Sl1nd

**Review by pfecht — APPROVED** [review]
Always good to get rid auf some code :) Looks good to me, the behaviour changed. No odd behaviour for me.

The only strange thing is that the datepicker loses focus on clicking the next month (was the same before). We should use icon-buttons here and render our custom markup (if possible).

But this could be addressed separately.

**Comment by janivo** [comment]
@pfecht: The focus thingy will be removed with #275 

Don't you have the same behaviour as @Sl1nd? For me, it behaves the same way shown in the video. 
Open Monthpicker -> Select Date -> Open it again -> Change year with the arrows at least twice -> See error

**Comment by janivo** [comment]
fixed in #275

**Pull request closed without merging**
