### PR TITLE
style(elements|ino-nav-item): restore original hover and active behavior

### PR DESCRIPTION
**Pull request by Sl1nd**
Closes #
https://github.com/inovex/elements/issues/202

## Proposed Changes

- Remove Ripple effect

### CODE REVIEW

**Review by janivo — CHANGES_REQUESTED** [review]
These changes disable the hover functionality of all `ino-list-item`s. I'll check for an alternative

**Comment by janivo** [comment]
@Sl1nd could you check if this works for you?

**Comment by Sl1nd** [comment]
I realized that also the `ino-list`checkbox behavior unintentionally changed in relation to the ripple Effect. Should it be fixed in that context as well?

**Comment by janivo** [comment]
No, I think this should be part of another PR

**Review by janivo — APPROVED** [review]

**Review by janivo — CHANGES_REQUESTED** [review]
The CSS Props have been removed for some reason

**Review by janivo — APPROVED** [review]

**Pull request merged**
