### PR TITLE
refactor(landingpage): removed german getting started guides

### LINKED ISSUE #971: Remove german getting started guides
...because they are not needed anymore as there is not enough demand for a german guide in relation to the maintenance effort.

### PR DESCRIPTION
**Pull request by BingeCode**
Closes #971 

## Proposed Changes

- Removed german guides
- Refactored getting started components (removed locale context)
- Added automatic disabled state on locale switcher component based on route

## Not added
- Note that informs the user that the guides are only available in English
- Perhaps leave the locale switcher enabled and only display the note when the user switches to or is in the german language context

### CODE REVIEW

**Comment by MariaLStefan** [comment]
And maybe we should make the sandbox bigger (full-screen?) because on a 15-inch screen it is quite a hassle to view everything

**Review by MariaLStefan — CHANGES_REQUESTED** [review]
The react start guide looks good 👍

The guides for JS, Angular and Vue still need some fixing. The "Looking for more resources" paragraph is now located where the chapter-navigation of the react guides sits. Additionally, the paragraph disappears on smaller screens. The Sandbox paragraph should be shown under the article, just like in the react guide. Could you look into that?

**Comment by MariaLStefan** [comment]
Fixed my requested changes:
- added sections to JavaScript, Angular & Vue guides to the navigation is shown
- styling improvement for inline code & code snippets

Responsibility issues remain, see  #1047

**Review by TobiasHeimGalindo — DISMISSED** [review]
Looks good to me :) ! I really like the styling improvement for the code snippets and inline code. I also refactored some typos I noticed along the way. If your satisfied with it feel free to merge 👍

**Review by TobiasHeimGalindo — APPROVED** [review]

**Review by MariaLStefan — APPROVED** [review]

**Review by MariaLStefan — APPROVED** [review]

**Pull request merged**
