### PR TITLE
ci: enable canary releases

### LINKED ISSUE #167: Canary releases
Add canary releases in order to provide consumers a fast way to upgrade to new features.

### Describe the solution you'd like
It would make the development much easier if the latest master would always be published to npm registry as canary deployment.

### Additional context
Lerna has such a feature and we could add such a script to package.json

```json
 "publish:canary": "yarn lerna publish --canary --exact --preid next.$(git rev-parse --short HEAD) --force-publish='*'"
```

This deploys a new version under the tag `canary` (we can change the tag with `--dist-tag`) and adds a version based on the last commit hash. It forces all packages to create a canary release and use the exact version to overcome conflicts resolving the correct version.

Canary deployments neither create a git commit nor a tag. We can add such canary release to the github pipeline in a similar way to the following gitlab ci script step:

```yaml
publish_package:
  stage: publish
  script:
    - PUPPETEER_SKIP_DOWNLOAD=true yarn 
    - yarn publish:canary
  only:
    - master
```

This requires the pipeline to be able to publish to npm registry.

### PR DESCRIPTION
**Pull request by janivo**
Closes #167 

## Proposed Changes

- Add script to create a canary release
- Run this script with every push to master in Github CI

### CODE REVIEW

**Comment by janivo** [comment]
Because lerna doesn't really have an option to run in dry run mode, it's hard to test if this really works. Maybe you guys can spot some issues beforehand. Otherwise, we might just have to test it in "production".

**Comment by pfecht** [comment]
Looks good to me, did you try publish it locally?

I wouldn't test it on master directly but change the rules to run it on this branch instead

**Comment by JCofman** [comment]
LGTM :)

**Review by JCofman — APPROVED** [review]

**Comment by janivo** [comment]
@pfecht: It should be working now and you can review this PR.

I know that there are some optimizations we can do. I'll open a ticket and do the optimization in a separate pr.

**Review by JCofman — APPROVED** [review]

**Pull request merged**
